# Doclink: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Code Coverage Badge

on:
  pull_request:
    types: [ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  build:

    runs-on: ubuntu-slim

    strategy:
      matrix:
        node-version: ["22.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    permissions:
      contents: write # needed to commit the changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm --omit=dev test -- --coverage # or run npm script

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: statements
          upload-badge: false     
          badge-path: "./test-passing-badge.svg"     

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          ref: ${{ github.head_ref }}
          file_pattern: './test-passing-badge.svg'  
